import { CustomSidebarLayout } from "@/components/test/CustomSidebarLayout";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const env = process.env.NODE_ENV

  if (env !== "development") {
    return <div>What are you doing here?</div>
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomSidebarLayout>
          {children}
        </CustomSidebarLayout>
      </body>
    </html >
  );
}
